version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: FSO22_Part13 Default is ?POSTGRES_USER?
    container_name: postgres-db
    ports:
      - 8080:5432
# Probably helpful to add a UI e.g. admine or pgAdmin img
