services:
  todo-frontend-prod:
    image: hello-front-prod
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-front-prod
    environment: # URL of the Reverse-proxy
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
  mongo-prod:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mondo_data:/data/db
    container_name: todo-mongo
  redis-prod:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_dada:/data
    container_name: todo-redis
  server-prod:
    image: todo-backend-prod
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo-server-prod
    environment:
      - REDIS_URL=redis://todo-redis:6379
      - MONGO_URL=mongodb://the_username:the_password@todo-mongo:27017/the_database
  nginx-rp:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - todo-frontend-prod
      - mongo-prod
      - redis-prod
      - server-prod
    container_name: nginx-reverse-proxy
