POST http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RAdGVzdC5jb20iLCJpZCI6MiwiaWF0IjoxNjY0OTc5MjEzfQ.8tD6JkSoYK_9n9a2cNiPQOLa_veezpNflm2I2g1OG1A
Content-Type: application/json

{
  "author": "website",
  "url": "https://jwt.io/",
  "title": "123",
  "year": "1991"
}
###
POST http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQHRlc3QuY29tIiwiaWQiOjEsImlhdCI6MTY2NDk3ODk4NX0.9yEZRtjBAEIbwoeTGjqVzVAYHyhUI4m43knc7nQnFHQ
Content-Type: application/json

{
  "author": "Docker goodness",
  "url": "https://fullstackopen.com/en/part12",
  "title": "Matti Luukkainen"
}
###
PUT http://localhost:3001/api/blogs/4
Content-Type: application/json

{
  "url": "test",
  "title": "test",
  "likes": 2
}
###
DELETE http://localhost:3001/api/blogs/2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RAdGVzdC5jb20iLCJpZCI6MiwiaWF0IjoxNjY0ODk2ODMwfQ.4MN64-aBSoQP8oETAaVp3XDdfl1Ng00EluVqmyOU0P8
###
GET http://localhost:3001/api/blogs
