POST http://localhost:3001/api/logout
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RAdGVzdC5jb20iLCJpZCI6MiwiaWF0IjoxNjY1MDQ1MzAzfQ.o7hMMWASI8MS1Fc4eCr76jMf8grgnqdzqYvVDTuFrDE
###